function [Times,VelocityCmSec,Radiuspx,MeanAngleAU,Locomotionbin,Whiskingbin,Stimulusbin] = importfile_s(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [TIMES,VELOCITYCMSEC,RADIUSPX,MEANANGLEAU,LOCOMOTIONBIN,WHISKINGBIN,STIMULUSBIN]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIMES,VELOCITYCMSEC,RADIUSPX,MEANANGLEAU,LOCOMOTIONBIN,WHISKINGBIN,STIMULUSBIN]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Times,VelocityCmSec,Radiuspx,MeanAngleAU,Locomotionbin,Whiskingbin,Stimulusbin] = importfile1('TS1006_2087_16_febbraio.csv',2, 23714);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/04/05 11:13:28

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Times = dataArray{:, 1};
VelocityCmSec = dataArray{:, 2};
Radiuspx = dataArray{:, 3};
MeanAngleAU = dataArray{:, 4};
Locomotionbin = dataArray{:, 5};
Whiskingbin = dataArray{:, 6};
Stimulusbin = dataArray{:, 7};


