function [] = plot_info_states_map(data,analyses,params)

if isfield(analyses,'info')
    if isfield(analyses.info,'info_states') && ~isempty(analyses.info.info_states)
        if isfield(analyses.info.info_states,'I_W') &&...
                isfield(analyses.info.info_states,'I_L') && ...
                isfield(analyses.info.info_states,'I_WL')
            subplot(1,2,1);
            imagesc(data.corr_projection); colormap('gray'); axis image;
            for indROI = 1:params.numROIs
                if analyses.info.info_states.I_WL(indROI)>analyses.info.info_states.I_W(indROI)
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        (analyses.info.info_states.I_WL(indROI)-analyses.info.info_states.I_W(indROI))*100,...
                        'MarkerFaceColor','r',...
                        'MarkerEdgeColor','r');
                elseif analyses.info.info_states.I_WL(indROI)<analyses.info.info_states.I_W(indROI)
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        (analyses.info.info_states.I_W(indROI)-analyses.info.info_states.I_WL(indROI))*100,...
                        'MarkerFaceColor','g',...
                        'MarkerEdgeColor','g');
                else
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        10,...
                        'MarkerFaceColor','y',...
                        'MarkerEdgeColor','y');
                end
                set(gca,'XTick',[],'yTick',[],'XTickLabel',{},'YTickLabel',{},...
                    'FontSize',10);
                title('r: I_{WL}>I_W, g: I_{WL}<I_W')
            end
            
            subplot(1,2,2);
            imagesc(data.corr_projection); colormap('gray'); axis image;
            for indROI = 1:params.numROIs
                if analyses.info.info_states.I_WL(indROI)>analyses.info.info_states.I_L(indROI)
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        (analyses.info.info_states.I_WL(indROI)-analyses.info.info_states.I_L(indROI))*100,...
                        'MarkerFaceColor','r',...
                        'MarkerEdgeColor','r');
                elseif analyses.info.info_states.I_WL(indROI)<analyses.info.info_states.I_L(indROI)
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        (analyses.info.info_states.I_L(indROI)-analyses.info.info_states.I_WL(indROI))*100,...
                        'MarkerFaceColor','g',...
                        'MarkerEdgeColor','g');
                else
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        10,...
                        'MarkerFaceColor','y',...
                        'MarkerEdgeColor','y');
                end
                set(gca,'XTick',[],'yTick',[],'XTickLabel',{},'YTickLabel',{},...
                    'FontSize',10);
                title('r: I_{WL}>I_L, g: I_{WL}<I_L')
            end
        elseif isfield(analyses.info.info_states,'I_WL') &&...
                isfield(analyses.info.info_states,'I_W')
            
            subplot(1,2,1);
            imagesc(data.corr_projection); colormap('gray'); axis image;
            for indROI = 1:params.numROIs
                if analyses.info.info_states.I_WL(indROI)>analyses.info.info_states.I_W(indROI)
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        (analyses.info.info_states.I_WL(indROI)-analyses.info.info_states.I_W(indROI))*100,...
                        'MarkerFaceColor','r',...
                        'MarkerEdgeColor','r');
                elseif analyses.info.info_states.I_WL(indROI)<analyses.info.info_states.I_W(indROI)
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        (analyses.info.info_states.I_W(indROI)-analyses.info.info_states.I_WL(indROI))*100,...
                        'MarkerFaceColor','g',...
                        'MarkerEdgeColor','g');
                else
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        10,...
                        'MarkerFaceColor','y',...
                        'MarkerEdgeColor','y');
                end
                set(gca,'XTick',[],'yTick',[],'XTickLabel',{},'YTickLabel',{},...
                    'FontSize',10);
                title('r: I_{WL}>I_W, g: I_{WL}<I_W')
            end
        elseif isfield(analyses.info.info_states,'I_WL') &&...
                isfield(analyses.info.info_states,'I_L')
            
            subplot(1,2,2);
            imagesc(data.corr_projection); colormap('gray'); axis image;
            for indROI = 1:params.numROIs
                if analyses.info.info_states.I_WL(indROI)>analyses.info.info_states.I_L(indROI)
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        (analyses.info.info_states.I_WL(indROI)-analyses.info.info_states.I_L(indROI))*100,...
                        'MarkerFaceColor','r',...
                        'MarkerEdgeColor','r');
                elseif analyses.info.info_states.I_WL(indROI)<analyses.info.info_states.I_L(indROI)
                    hold on; scatter(data.rois_centers(indROI,2),...
                        data.rois_centers(indROI,1),...
                        (analyses.info.info_states.I_L(indROI)-analyses.info.info_states.I_WL(indROI))*100,...
                        'MarkerFaceColor','g',...
                        'MarkerEdgeColor','g');
                else
                    hold on; scatter(rois_centers(indROI,2),...
                        rois_centers(indROI,1),...
                        10,...
                        'MarkerFaceColor','y',...
                        'MarkerEdgeColor','y');
                end
                set(gca,'XTick',[],'yTick',[],'XTickLabel',{},'YTickLabel',{},...
                    'FontSize',10);
                title('r: I_WL>I_L, g: I_WL<I_L')
            end
        end

    end
end

